### ISSUE TITLE
Biome Colors Glitch

### ISSUE THREAD

**Issue by legosteenjaap** [AkashiiKun/CavesCliffsPartTwoMod#1]
![image](https://user-images.githubusercontent.com/50271899/123975615-c578b280-d9bd-11eb-928e-f743b9f6523e.png)
![image](https://user-images.githubusercontent.com/50271899/123975691-d295a180-d9bd-11eb-81ec-3d1dbd1cafb3.png)
Biome colors in a swamp are glitched when a lush cave is underneath.

![image](https://user-images.githubusercontent.com/50271899/123975971-0ffa2f00-d9be-11eb-8483-af71926e83e4.png)
Dripstone cave with deep luke warm ocean on the left and a deep luke warm ocean with normal caves on the right. Both sides should be the same color because they are both luke warm oceans.

![image](https://user-images.githubusercontent.com/50271899/123976572-8a2ab380-d9be-11eb-99b9-ff26312cf48e.png)

**Comment by AkashiiKun** [comment]
Thanks for reporting, but right now is working as intended, we'll work into a fix at some point. ^^

**Comment by legosteenjaap** [comment]
How is this intended?
![image](https://user-images.githubusercontent.com/50271899/123990923-856bfc80-d9ca-11eb-98c6-e7916298ad5f.png)

**Comment by AkashiiKun** [comment]
Because currently vanilla client doesn't support 3d biomes, and fixing it would be harder than actually waiting for mojang's implementation,

**Comment by legosteenjaap** [comment]
Isn't it the point of this mod to port those features to 1.17

**Comment by AkashiiKun** [comment]
I've just seen that you are implementing it, if you want to help i would be glad to implement it into my mod. ^^

**Comment by legosteenjaap** [comment]
#3

**Comment by legosteenjaap** [comment]
is the fix
