### ISSUE TITLE
Probably a reason to stop developing this mod OR try to make it better using it's API...

### ISSUE THREAD

**Issue by AkashiiKun** [AkashiiKun/CavesCliffsPartTwoMod#15]
https://github.com/ItsBlackGear/CaveBiomeAPIFabric

Check this out... @legosteenjaap @Justsnoopy30

**Comment by legosteenjaap** [comment]
eh idk, it doesn't add extra worldheight

**Comment by AkashiiKun** [comment]
but it does load the new caves, and supports changing height via datapack

**Comment by AkashiiKun** [comment]
also, on theirs there are no bugs at all

**Comment by legosteenjaap** [comment]
![image](https://user-images.githubusercontent.com/50271899/124272689-5dea7080-db3f-11eb-8b33-e68debaa09b5.png)
found this bug in their mod

![image](https://user-images.githubusercontent.com/50271899/124272911-af92fb00-db3f-11eb-9a94-84aa63022d3a.png)
and this bug

and they also have the bug where no mobs spawn above ground.

And we could take a look at their mixins to make our mixins a bit better.

**Comment by AkashiiKun** [comment]
i mean... the mobs do spawn
they don't if you're in spectator
about the grass, yea, could be fixed and also the azalea trees spawning

**Comment by AkashiiKun** [comment]
Mobs do spawn  ^^
![image](https://user-images.githubusercontent.com/44606942/124276828-38a83300-db3c-11eb-9589-0e197d1e28aa.png)
![image](https://user-images.githubusercontent.com/44606942/124276882-4a89d600-db3c-11eb-9cb8-3f22376c33b4.png)

**Comment by legosteenjaap** [comment]
Why are there mobs spawning hmm weird

**Comment by AkashiiKun** [comment]
because they fixed it.

**Comment by AkashiiKun** [comment]
anyways, the license of the API is MIT so we can take it and improve it for our needs ^^

**Comment by legosteenjaap** [comment]
ye

**Comment by AkashiiKun** [comment]
also, accept the contribution invite so you can work directly without needing to make pull requests

**Comment by ItsBlackGear** [comment]
honestly i don't think that it is required to use the code of my API to use it for the vanilla cave biome generation exclusively
