### ISSUE TITLE
Dripstones generating on the ocean floor and underwater

### ISSUE THREAD

**Issue by legosteenjaap** [AkashiiKun/CavesCliffsPartTwoMod#7]
Dripstone blocks and pointed dripstone should not be able to spawn underwater.
![image](https://user-images.githubusercontent.com/50271899/124139005-7a2ad680-da87-11eb-95fe-69bbbf933c77.png)

Because in real life stalagmites and stalactites can't form underwater.

**Comment by legosteenjaap** [comment]
![image](https://user-images.githubusercontent.com/50271899/124176852-c427b280-daaf-11eb-8efd-a165237c6930.png)

**Comment by legosteenjaap** [comment]
seed: 4895219545960988366

**Comment by AkashiiKun** [comment]
I'm aware of that

**Comment by legosteenjaap** [comment]
fixed everything except moss generating underwater

**Comment by AkashiiKun** [comment]
Thanks ^^
